name: e2e
on: push
concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: install node 22
        uses: actions/setup-node@v6
        with:
          node-version: '22'
      - name: npm install
        run: npm install
      - name: build
        run: npm run build
      - name: install Playwright browsers
        run: npx playwright install --with-deps --no-shell chromium
      - name: test log
        run: |
          ls -l Build/Specs
          ls -l Specs/e2e
      - name: run e2e tests
        run: npm run test-e2e -- viewer.spec.js
      - name: test log 2
        run: |
          ls -l Build/Specs
          ls -l Specs/e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: e2e-report
          path: Build/Specs/e2e/report/
          retention-days: 30
